### PR TITLE
Shaved another couple minutes off Zaragoza route.

### PR DESCRIPTION
**Pull request by kbtbc**

### CODE REVIEW

**Comment by plinytheelder** [comment]
can confirm. Ran this yesterday and average dropped from ~15m-16m to 13m-14m

nice job!

**Comment by Fabio1988** [comment]
But it's also 80 locations less... Can we confirm we don't run into Cooldown of stops?

Was this also tested with leveling to 31?

How did you create it, focussed on spawnpoints only ir a mix of forts/spawnpoints?

**Comment by kbtbc** [comment]
I've leveled hundreds on this route and it consistently ends around stop #90, so I think 120 is more than sufficient.  
Not tested for 31 (I personally have no interest in)
I used secret advanced tools to create that I cannot share...   jk, I just looked at a map with forts/spawnpoints and plotted the circles by hand.  :-)

**Comment by jfberry** [comment]
31 is needed for some quests so it would be nice to know it was long enough for this (which is why we build support for making and choosing level 31 workers)

**Comment by plinytheelder** [comment]
Just looked it up

https://discord.com/channels/1083029607919386654/1083487483175633017/1174008628131397672

**Comment by Fabio1988** [comment]
> Just looked it up
> 
> https://discord.com/channels/1083029607919386654/1083487483175633017/1174008628131397672

that's wrong.. max revive can be obtained from level 30+

**Comment by kbtbc** [comment]
So, you would have had to rescan for quests at event start with only level 31 accounts?     Has level 31 req for questing been observed other than that event?  

  For practical reasons (and given the much greater time required to hit level 31) shouldn't the setting in dragonite `#required_level = 31 # used for everything except leveling (quest can force level 31 at specific events)` only adjust the level requirement for questing, not 'everything'?   Including everything such as pokemon scanning where level 31 makes no diff seems to be placing an unnecessary burden on the needed number of L31 accounts for such use cases.

**Comment by kbtbc** [comment]
I have now tested L31, and it works fine on this route.  Hits level 31 in ~20-21m around or before location #110.

**Comment by jfberry** [comment]
> So, you would have had to rescan for quests at event start with only level 31 accounts? Has level 31 req for questing been observed other than that event?

This is a separate discussion not related to this issue (beyond ensuring it can get to 31).  Currently all accounts are equivelant in dragonite to manage the long-term time-out forced on us, and I don't see that changing in the short term.

**Comment by kbtbc** [comment]
There are many variables about the health and need of accounts.   Device type, warns, suspends, time to create, time until banned, etc. ... and for public, having ready accounts is further limited by avail tools and license costs.    Any consideration that reduces account burden & their cost requirements is greatly appreciated, even part of the longer term plan.   Cheers

**Comment by kbtbc** [comment]
On topic:    This is a tested, improved Zaragoza route that works great for both level 30 and 31!
   Thanks to Pliny for the original.    Enjoy!  :-)

**Comment by notheowner** [comment]
LGTM
image

**Pull request merged**
