### PR TITLE
chore: update config examples

### PR DESCRIPTION
**Pull request by Fabio1988**
to provide auth provider config examples

### CODE REVIEW

**Comment by jfberry** [comment]
This math is not reliable and should not be referred to in config.

**Comment by Fabio1988** [comment]
> This math is not reliable and should not be referred to in config.

Updated... I wonder if it's good like that, or we should put more/less information/comments. Or should we only keep one section and putting the provider defaults as comments?

**Comment by jfberry** [comment]
Each provider has different defaults but there is almost no reason to change the timings/concurrencies unless you really understand what interactions they cause

**Comment by Fabio1988** [comment]
> Each provider has different defaults but there is almost no reason to change the timings/concurrencies unless you really understand what interactions they cause

So removing those from example and put in in docs for more information?

**Comment by Fabio1988** [comment]
Removed some configs from here. Instead put it into the docs page.. there we can describe them and put a warning :)

https://github.com/UnownHash/docs/pull/35

**Pull request merged**
